# Generated by Django 4.0.4 on 2022-05-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=40, verbose_name='Nombre')),
                ('ap', models.CharField(max_length=40, verbose_name='Apellido Paterno')),
                ('am', models.CharField(max_length=40, verbose_name='Apellido Materno')),
                ('dir', models.TextField(null=True, verbose_name='Dirección')),
                ('foto', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Foto')),
            ],
        ),
    ]
